### ISSUE TITLE
Feature request: instead of "away", present the actual address

### ISSUE THREAD

**Issue by zivgin** [Vedeneb/HA-SmartThings-Find#14] opened 2024-06-20 13:09 UTC
I'd like to have the ability to hold the exact address of where the sensor is located.
Right now, if it's not in defined areas, it just shows "Away" which isn't very practical.
It would be great to get the exact location of the sensor.

**Comment by Vedeneb** [comment] 2024-06-20 13:12
This is how device trackers work in Home Assistant, there's nothing this integration can do about it because this data is not available on the SmartThings Find website either.
You have the coordinates in the device_tracker attributes, you could try to use an external tool to find a location based on the coordinates.

Also, this is a duplicate of #7.

**Closed as not planned by Vedeneb** 2024-06-20 13:12 UTC
Labels: duplicate

**Comment by zivgin** [comment] 2024-06-20 13:17
Thank you!
Where can i see the geo location? i couldn't see it

**Comment by Vedeneb** [comment] 2024-06-20 13:20
As I said, there is no geo location as the SmartThings Find website does not provide this information.

If you refer to the coordinates, they are just normal attributes. Just open the more-info dialog and expand the attribute section. Here you will find the "Latitude" and "Longitude".
